version: '2.2'

services:
  task-force:
    container_name: backend
    image: node:12.18.4
    build: ./
    command: npm run dev
    working_dir: /usr/src/task-force
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/task-force

  #adding mongo db
  database:
    container_name: mongoDb
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - '27017:27017'
